name: Clone Staging Database

on:
  # these will be uncommented after testing
  # ----
  # schedule:
  #   # Run daily at 2:00 PM EST
  #   - cron: '0 * * * *'
  # Allow manual triggering
  workflow_dispatch:

env:
  DESTINATION_ENVIRONMENT: ms
  SOURCE_ENVIRONMENT: staging
  

jobs:
  clone-database:
    runs-on: ubuntu-latest
    env:
      CF_USERNAME: CF_MS_USERNAME
      CF_PASSWORD: CF_MS_PASSWORD
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Share DB Service
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{ secrets[env.CF_USERNAME] }}
          cf_password: ${{ secrets[env.CF_PASSWORD] }}
          cf_org: cisa-dotgov
          cf_space: ${{ env.DESTINATION_ENVIRONMENT }}
          cf_command: share-service getgov-${{ env.DESTINATION_ENVIRONMENT }}-database -s ${{ env.SOURCE_ENVIRONMENT }}

      - name: Clone Database
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{ secrets.CF_MS_USERNAME }}
          cf_password: ${{ secrets.CF_MS_PASSWORD }}
          cf_org: cisa-dotgov
          cf_space: ${{ env.SOURCE_ENVIRONMENT }}
          command: cg-manage-rds clone getgov-${{ env.SOURCE_ENVIRONMENT }}-database getgov-${{ env.DESTINATION_ENVIRONMENT }}-database
      
      - name: Unshare DB Service
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{ secrets.CF_MS_USERNAME }}
          cf_password: ${{ secrets.CF_MS_PASSWORD }}
          cf_org: cisa-dotgov
          cf_space: ${{ env.SOURCE_ENVIRONMENT }}
          cf_command: unshare-service getgov-${{ env.DESTINATION_ENVIRONMENT }}-database -s ${{ env.SOURCE_ENVIRONMENT }}
